---
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: audit-service-task-events
spec:
  topic: task-events
  route: /task-events
  pubsubname: taskpubsub
  scopes:
    - audit-service
