# Dapr subscription configuration for WebSocket Service
# This file defines the pub/sub subscriptions declaratively
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: websocket-task-updates-subscription
  namespace: todo-app
spec:
  topic: task-updates
  routes:
    - task-updates  # Route to the subscription endpoint
  pubsubname: taskpubsub
  scopes:
    - websocket-service
