"""update_tables_with_enhanced_fields

Revision ID: 516fd03e8a42
Revises: e815a6193a17
Create Date: 2025-12-13 02:59:06.464728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '516fd03e8a42'
down_revision: Union[str, None] = 'e815a6193a17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_category_name'), 'task_categories', type_='unique')
    op.drop_constraint(op.f('task_categories_user_id_fkey'), 'task_categories', type_='foreignkey')
    op.create_foreign_key(None, 'task_categories', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_categories', type_='foreignkey')
    op.create_foreign_key(op.f('task_categories_user_id_fkey'), 'task_categories', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_user_category_name'), 'task_categories', ['user_id', 'name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
